### ISSUE TITLE
[whales, task 7] AttributeError("Can't pickle local object 'solution.<locals>.DatasetLocalizer'",))

### ISSUE THREAD

**Issue by rafajak** [neptune-ml/minerva-training-materials#79]
`neptune run main.py -- submit --problem whales --task_nr 7
`

the above results in the error below. 

```10.418098 | [NbConvertApp] Converting notebook /mnt/ml-team/homes/usr/minerva/resources/whales/tasks/task7.ipynb to python
-- | --
12.114279 | [NbConvertApp] Writing 4898 bytes to /mnt/ml-team/homes/usr/minerva/resources/whales/tasks/task7.py
12.612039 | /mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
12.612379 | from ._conv import register_converters as _register_converters
13.203399 | Using TensorFlow backend.
25.387684 | Traceback (most recent call last):
25.387881 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 103, in execute
25.388077 | execfile(job_filepath, job_globals)
25.388271 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/past/builtins/misc.py", line 82, in execfile
25.388466 | exec_(code, myglobals, mylocals)
25.388659 | File "main.py", line 66, in <module>
25.388854 | action()
25.389049 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
25.389249 | return self.main(*args, **kwargs)
25.389443 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/click/core.py", line 697, in main
25.389637 | rv = self.invoke(ctx)
25.38983 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
25.390016 | return _process_result(sub_ctx.command.invoke(sub_ctx))
25.390203 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
25.39039 | return ctx.invoke(self.callback, **ctx.params)
25.390576 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
25.390775 | return callback(*args, **kwargs)
25.390969 | File "main.py", line 61, in submit
25.391163 | pm.submit_task(task_sub_problem, task_nr, file_path, dev_mode)
25.391356 | File "/mnt/ml-team/homes/usr/minerva/minerva/whales/problem_manager.py", line 44, in submit_task
25.391565 | new_trainer.train()
25.39176 | File "/mnt/ml-team/homes/usr/minerva/minerva/whales/trainer.py", line 48, in train
25.391954 | 'train_mode': True,
25.392147 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/base.py", line 75, in fit_transform
25.392339 | step_inputs[input_step.name] = input_step.fit_transform(data)
25.392535 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/base.py", line 75, in fit_transform
25.392728 | step_inputs[input_step.name] = input_step.fit_transform(data)
25.392918 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/base.py", line 81, in fit_transform
25.393109 | step_output_data = self._cached_fit_transform(step_inputs)
25.393302 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/base.py", line 91, in _cached_fit_transform
25.393489 | step_output_data = self.transformer.fit_transform(**step_inputs)
25.393675 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/base.py", line 218, in fit_transform
25.39386 | self.fit(*args, **kwargs)
25.394049 | File "/mnt/ml-team/homes/usr/minerva/minerva/backend/models/pytorch/models.py", line 55, in fit
25.394249 | for batch_id, data in enumerate(batch_gen):
25.394443 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
25.394635 | return DataLoaderIter(self)
25.394829 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 234, in __init__
25.395021 | w.start()
25.395211 | File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
25.395401 | self._popen = self._Popen(self)
25.395623 | File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
25.395817 | return _default_context.get_context().Process._Popen(process_obj)
25.396009 | File "/usr/lib/python3.5/multiprocessing/context.py", line 274, in _Popen
25.396201 | return Popen(process_obj)
25.396396 | File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 33, in __init__
25.396587 | super().__init__(process_obj)
25.396777 | File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
25.396966 | self._launch(process_obj)
25.397153 | File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 48, in _launch
25.39734 | reduction.dump(process_obj, fp)
25.397531 | File "/usr/lib/python3.5/multiprocessing/reduction.py", line 59, in dump
25.397722 | ForkingPickler(file, protocol).dump(obj)
25.397914 | AttributeError: Can't pickle local object 'solution.<locals>.DatasetLocalizer'
25.398359 |  
25.398564 | During handling of the above exception, another exception occurred:
25.398762 |  
25.398955 | Traceback (most recent call last):
25.399148 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 109, in <module>
25.399342 | execute()
25.413426 | File "/mnt/ml-team/homes/usr/envs/minerva_venv/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 105, in execute
25.413676 | raise ExperimentExecutionException("Exception during experiment execution", ex)
25.413876 | deepsense.neptune.exceptions.ExperimentExecutionException: ('Exception during experiment execution', AttributeError("Can't pickle local object 'solution.<locals>.DatasetLocalizer'",))


```

**Comment by kamil-kaczmarek** [comment]
resolved in #89
